apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service-app
  labels:
    app: volunteer-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service-app
  template:
    metadata:
      labels:
        app: volunteer-service-app
    spec:
      containers:
        - name: volunteer-service-app
          image: ayga/service-volunteer
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: "volunteer-Service"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka:8761/eureka/"
            - name: SERVER_PORT
              value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: volunteer-service-svc
spec:
  type: NodePort
  ports:
    - name: volunteer-app-service-port
      port: 8081
      targetPort: 8081
      nodePort: 30009
      protocol: TCP
  selector:
    app: volunteer-app
