apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim-service-app
  labels:
    app: victim-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim-service-app
  template:
    metadata:
      labels:
        app: victim-service-app
    spec:
      containers:
        - name: victim-service-app
          image: ayga/service-victim
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              value: "Victim-Service"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka:8761/eureka/"
            - name: SERVER_PORT
              value: "8082"

---
apiVersion: v1
kind: Service
metadata:
  name: victim-service-svc
spec:
  type: NodePort
  ports:
    - name: victim-app-service-port
      port: 8082
      targetPort: 8082
      nodePort: 30006 # You can specify a different nodePort if needed
      protocol: TCP
  selector:
    app: victim-app
